# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: pandoc/latex

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Print Status
      - name: Print start
        run: echo Pushing to the other repository

      - name: Pushes to another repository
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.TEST_GITHUB_ACTIONS_SECRET }}
        with:
          source-directory: '.'
          destination-github-username: 'BogsBalangat'
          destination-repository-name: 'github-action-dest'
          user-email: bogs@maliksi.io
          target-branch: main

      # Print Status
      - name: Print end
        run: echo Pushed to the other repository
